---
title: "My Webpage"
author: "Anna Talucci"
date: "October 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
esc = read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), stringsAsFactors = FALSE)
```

# Calculate Annual Escapement for Salmon Species

```{r, results = "hide"}
species_list = c("Chinook", "Sockeye", "Chum", "Pink", "Coho")

annual_esc = esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = FALSE) %>% 
  mutate(Year = as.numeric(Year)) %>% 
    group_by(Year, SASAP.Region, Species) %>%
  summarise(total_esc = sum(DailyCount)) %>%
  filter(Species %in% species_list)
  #filter(Species %in% c("Chinook", "Sockeye", "Chum", "Pink", "Coho"))


head(annual_esc)
```

Calculate total annual escapement by region, year, and species

`%in%` 

```{r}
# total_esc = annual_esc %>% 
#   group_by(Year, SASAP.Region, Species) %>%
#   summarise(total = sum(DailyCount)) %>%
#   filter(Species %in% c("Chinook", "Sockeye", "Chum", "Pink", "Coho"))
# 
# head(total_esc)
```

# Visualize escapement

Total escapement by Region and Species

```{r, echo = FALSE}
ggplot(data = annual_esc, mapping = aes(x = Species, y = total_esc, fill = SASAP.Region)) +
  geom_col() 
  
```

Kodiak escapement over time by species

```{r, echo = FALSE}
my_theme = theme_bw() +
  theme(legend.position = "bottom")

ggplot(data = filter(annual_esc, SASAP.Region == "Kodiak"), 
       mapping = aes(x = Year, y = total_esc, color = Species)) +
  geom_point() +
  geom_line() +
  scale_color_brewer(palette = "Dark2") +
  ylab("Escapement (no. fish)") +
  ggtitle("Kodiak Salmon Escapement") +
  my_theme

```

Escapement over time: all regions

```{r, fig.width = 7, fig.height = 20}
ggplot(annual_esc, aes(x = Year, y = total_esc, colour = Species)) +
  geom_point() +
  geom_line() +
  facet_wrap(~SASAP.Region, scales = "free_y", ncol = 1) +
  my_theme
```


# Map sampling locations
